image: docker:latest
services:
- docker:dind
variables:
  DOCKER_DRIVER: overlay
before_script:
- docker info
- apk add -U openssl curl bash
- curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/darwin/amd64/kubectl
- chmod +x ./kubectl
- mv ./kubectl /usr/local/bin/kubectl
- kubectl version --client

build:
  stage: build
  only:
  - master
  script:
  - echo $CI_BUILD_REF_NAME
  - echo $CI_BUILD_REF
  - echo $CI_PIPELINE_ID
  - kubectl config set-cluster $GCE_CLUSTER_NAME --server=$GCE_CLUSTER_URL
  - kubectl config set-credentials $GCE_USER_NAME --token=GCE_TOKEN
  - kubectl config set-context gce --user=$GCE_USER_NAME --cluster=$GCE_CLUSTER_NAME
  - kubectl config use-context gce
  - kubectl get pods