image: docker:latest
services:
- docker:dind
variables:
  DOCKER_DRIVER: overlay

build:
  image: google/cloud-sdk
  stage: build
  only:
  - master
  script:
  - echo $CI_BUILD_REF_NAME
  - echo $CI_BUILD_REF
  - echo $CI_PIPELINE_ID
  - echo "$GCE_KEY" > key.txt
  - base64 -i key.txt -d > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set compute/zone $GCE_CLUSTER_ZONE
  - gcloud config set project midnight-lizard
  - gcloud config set container/use_client_certificate True
  - gcloud container clusters get-credentials $GCE_CLUSTER_NAME
  - kubectl get pods