image: docker:latest
services:
- docker:dind
variables:
  DOCKER_DRIVER: overlay
before_script:
- docker info
- curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/latest.txt)/bin/linux/amd64/kubectl && \
  chmod +x /usr/bin/kubectl && \
  kubectl version --client

stages:
  - build
  - test
  - deploy
build:
  stage: build
  only:
  - master
  script:
  - echo $CI_BUILD_REF_NAME
  - echo $CI_BUILD_REF
  - echo $K8S_TOKEN
  - echo $K8S_URL