image: docker:latest
services:
- docker:dind
variables:
  DOCKER_DRIVER: overlay
  PROJ: portal
  GROUP: midnight-lizard

gce-deploy:
  image: google/cloud-sdk
  stage: deploy
  only:
  - master
  script:
  - ./shell/gcloud-config.sh -k $GCE_KEY -z $GCE_CLUSTER_ZONE -p $GROUP -c $GCE_CLUSTER_NAME;
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash;
  - ./shell/helm-deploy.sh -i $CI_REGISTRY/$GROUP/$PROJ:12814158 -r $PROJ -c ./kube/$PROJ