image: docker:latest
services:
- docker:dind
variables:
  DOCKER_DRIVER: overlay
before_script:
- docker info
- apk add -U openssl curl bash ca-certificates
- curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl
- chmod +x /usr/bin/kubectl
- kubectl version --client

build:
  stage: build
  only:
  - master
  script:
  - echo $CI_BUILD_REF_NAME
  - echo $CI_BUILD_REF
  - echo $CI_PIPELINE_ID
  - kubectl config set-cluster $GCE_CLUSTER_NAME --server=$GCE_CLUSTER_URL --insecure-skip-tls-verify=true
  - kubectl config set-credentials $GCE_USER_NAME --user=$GCE_USER_NAME --password=$GCE_USER_PASSWORD
  - kubectl config set-context gce --user=$GCE_USER_NAME --cluster=$GCE_CLUSTER_NAME
  - kubectl config use-context gce
  - kubectl get pods