# Default values for portal.
replicaCount: 1
image: portal:latest
pullPolicy: IfNotPresent
antiAffinity:
  weight: 100
  apps:
    - schemes
    - identity
service:
  name: portal
  type: NodePort
  externalPort: 80
  internalPort: 80
  debugPort: 9229
env:
  IDENTITY_URL: http://identity.midnight-lizard.online
  PORTAL_URL: http://midnight-lizard.online