# Default values for portal.
replicaCount: 1
image: portal:latest
pullPolicy: IfNotPresent
service:
  name: portal
  type: NodePort
  externalPort: 80
  internalPort: 80
  debugPort: 9229
secrets:
  sessionSecret: "base64 encoded value"
env:
  USE_AUTH: true
  IDENTITY_URL: https://identity.midnight-lizard.org
  PORTAL_URL: https://midnight-lizard.org
  SCHEMES_QUERIER_URL: https://schemes-querier.midnight-lizard.org
  SCHEMES_COMMANDER_URL: https://schemes-commander.midnight-lizard.org
  IMPRESSIONS_COMMANDER_URL: https://impressions-commander.midnight-lizard.org
  PORTAL_USER_AUTH_REFRESH_INTERVAL: 270000
  PORTAL_SYSTEM_AUTH_REFRESH_INTERVAL: 270000
