# Default values for portal.
replicaCount: 1
image: portal:latest
pullPolicy: IfNotPresent
antiAffinity:
  weight: 100
  apps:
    - identity
service:
  name: portal
  type: NodePort
  externalPort: 80
  internalPort: 80
  debugPort: 9229
secrets:
  sessionSecret: "base64 encoded value"
env:
  USE_AUTH: true
  IDENTITY_URL: https://identity.midnight-lizard.org
  PORTAL_URL: https://midnight-lizard.org
  SCHEMES_QUERIER_URL: https://schemes-querier.midnight-lizard.org
  SCHEMES_COMMANDER_URL: https://schemes-commander.midnight-lizard.org
  PORTAL_AUTH_REFRESH_INTERVAL: 240000
