# Default values for portal.
replicaCount: 1
image: portal:latest
pullPolicy: IfNotPresent
antiAffinity:
  weight: 100
  apps:
    - schemes
    - identity
service:
  name: portal
  type: NodePort
  externalPort: 80
  internalPort: 80
env:
  ASPNETCORE_ENVIRONMENT: Production
  ENV: prod
  NODE_ENV: production
  SCHEMES_URL: http://schemes.midnight-lizard.online
  IDENTITY_URL: http://identity.midnight-lizard.online