version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2
    environment:
      - ENV=prod
    volumes:
      - ..:/src
    working_dir: /src
    command: >
      /bin/bash -c "
        dotnet restore ./MLPortal.sln &&
        dotnet publish ./MLPortal.sln -c Release -o ./obj/Docker/publish"
