version: '3'

services:
  build:
    image: build
    environment:
      - ENV=prod
    volumes:
      - ..:/src
    command: >
      /bin/bash -c "
        cp -r /src /build &&
        cd /build &&
        rm -r ./App/node_modules &&
        dotnet restore ./MLPortal.sln &&
        dotnet publish ./MLPortal.sln -c Release -o ./obj/Docker/publish"
